"""rename address

Revision ID: 1341f9ad2775
Revises: bbb1e5ae07a1
Create Date: 2025-12-19 08:01:39.889223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1341f9ad2775'
down_revision = 'bbb1e5ae07a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
