"""add adddress

Revision ID: bbb1e5ae07a1
Revises: 7b732f7f76ba
Create Date: 2025-12-19 07:46:56.098321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb1e5ae07a1'
down_revision = '7b732f7f76ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('departments', 'budget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('budget', sa.INTEGER(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###
